######################################################################
# Automatically generated by qmake (2.01a) Mon May 2 20:01:35 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += debug
QT += network
# Input
HEADERS += ChatServer.h ChatServerThread.h
SOURCES += ChatServer.cpp ChatServerThread.cpp main.cpp
